### ISSUE TITLE
Download URL is broken in brew

### ISSUE THREAD

**Issue by volkan-a** [gerlero/homebrew-openfoam#40]
Hi,

I don't know if it's the right the place but download link in brew is broken. I got the error message below:

```
 ~/ brew reinstall openfoam2206
==> Downloading https://github.com/gerlero/openfoam-app/releases/download/v1.8.1/openfoam22
curl: (22) The requested URL returned error: 404

Error: Download failed on Cask 'openfoam2206' with message: Download failed: https://github.com/gerlero/openfoam-app/releases/download/v1.8.1/openfoam2206-app-homebrew-.zip
```

**Comment by gerlero** [comment]
Good catch. Cask `openfoam2112` is broken in the same way. Brew's suggested syntax update in #37 and #38 got it wrong, so that the `arch` variable is not actually set, leading to a bad URL. The right way to define `arch` in a cask seems to be as in https://github.com/Homebrew/homebrew-cask/pull/129480.

**Comment by gerlero** [comment]
Should be fixed now (a `brew update` might be needed to get the new definitions). Thank you @volkan-a!
