### ISSUE TITLE
Scotch server is down

### ISSUE THREAD

**Issue by BrushXue** [gerlero/homebrew-openfoam#70]
Currently there's a temporary server down, but I found an alternative link from ubuntu. You may add a backup link to the recipe like
```
mirror "http://archive.ubuntu.com/ubuntu/pool/universe/s/scotch/scotch_6.1.3.orig.tar.xz"
```
However I don't know how to handle the different SHA256. Maybe just skip it?

**Comment by gerlero** [comment]
I can confirm that the server is down.  Do you know how long it's been that way? If it's just under some "weekend maintenance" I'd prefer to just wait it out...

I've been able to retrieve the cached source tarball from my machine at `~/Library/Caches/Homebrew/scotch-no-pthread--6.1.3.tar.bz2`. I'm attaching the file to this message (note: had to change the final `bz2` extension to `zip` so that GitHub would let me upload it). You can check that it has the same SHA256 as the formula, i.e.:

https://github.com/gerlero/homebrew-openfoam/blob/ed273c16ead4ffe1754deb03a1c0d69ae490fa17/Formula/scotch-no-pthread.rb#L5

[scotch-no-pthread--6.1.3.tar.zip](https://github.com/gerlero/homebrew-openfoam/files/11926972/scotch-no-pthread--6.1.3.tar.zip)

If the upstream server doesn't come back online and there's no other indication on where to get the official sources, then there's the possibility to temporarily point the formula to that file (while being able to retain the SHA256 check). Or in that case, just do what Homebrew chooses to do with their formula, which has to be affected by the same problem.

**Comment by BrushXue** [comment]
I couldn't figure out how to install it with the cached tarball you provided. Homebrew still requires the response from their server.
```
Error: Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.26-29-g9a482de\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 12.6.7\)\ curl/7.87.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://gitlab.inria.fr/scotch/scotch/-/archive/v6.1.3/scotch-v6.1.3.tar.bz2` exited with 7. Here's the output:
curl: (7) Failed to connect to gitlab.inria.fr port 443 after 211 ms: Couldn't connect to server
```

**Comment by gerlero** [comment]
I think you might be able to edit your local copy of the formula file (at `/opt/homebrew/Library/Taps/gerlero/homebrew-openfoam/Formula/scotch-no-pthread.rb`) to point it at the other tarball

**Comment by BrushXue** [comment]
For anyone who can't install this recipe due to `gitlab.inria.fr` connection issue, I made a temporary recipe pointing at the cache of Ubuntu repository:
[scotch-no-pthread.rb.zip](https://github.com/gerlero/homebrew-openfoam/files/11929971/scotch-no-pthread.rb.zip)
Download and run `brew install scotch-no-pthread.rb`

**Comment by gerlero** [comment]
Server is back online (site says it was undergoing planned weekend maintenance)
